# Generated by Django 5.0.1 on 2024-01-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('context', models.TextField(blank=True)),
                ('create_add', models.DateTimeField(auto_now_add=True)),
                ('update_add', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photo')),
                ('is_publish', models.BooleanField(default=True)),
            ],
        ),
    ]
