# Generated by Django 5.0.1 on 2024-02-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='VIdeo',
        ),
    ]
